var express = require('express');
var router = express.Router();


var glossery = [
  {terminology: "DevOps", description: "DevOps is a set of practices and cultural philosophies that aim to bridge the gap between software development (Dev) and IT operations (Ops). It promotes collaboration, communication, and integration between development and operations teams throughout the software development lifecycle.", reference: "'DevOps,' Atlassian. Available: https://www.atlassian.com/devops."},
  {terminology: "Agile Development", description: "Software development using the agile methodology places a strong emphasis on adaptability, client collaboration, and responsiveness to changing requirements. It encourages flexible planning, regular software delivery, and ongoing development via frequent feedback loops.", reference: "Atlassian, 'Agile,' Atlassian. Available: https://www.atlassian.com/agile."},
  {terminology: "Test-Driven Development (TDD)", description: "Test-Driven Development (TDD) is a development technique where the developer first writes a test before writing the production code to fulfill that test. This approach emphasizes the creation of tests that define and validate what the code will do.", reference: "Atlassian, 'Test-driven development (TDD)', Atlassian Agile Coach. Available: https://www.atlassian.com/agile/software-development/"},
  {terminology: "Serverless Architecture", description: "Serverless architectures allow developers to build and run applications and services without thinking about servers. With serverless architectures, your application still runs on servers, but all the server management is done by AWS.", reference: "Amazon Web Services, 'What is Serverless?', AWS. Available: https://aws.amazon.com/serverless/."},
  {terminology: "CI/CD Pipeline", description: "A CI/CD Pipeline is a series of steps that software must go through, from initial code push, to high-level testing, to deployment. CI stands for Continuous Integration, a software development practice where developers regularly merge their code changes into a central repository, followed by automated building and testing. CD stands for Continuous Delivery or Continuous Deployment, practices that further the automation, including the release process.", reference: "Red Hat, 'CI/CD,' Red Hat. Available: https://www.redhat.com/en/topics/devops/what-is-ci-cd"},
  {terminology: "Configuration Management", description: "Configuration management (CM) in a DevOps context, is the process of systematically managing, organizing, and controlling the changes in the documents, codes, and other entities during the software development process. It ensures that the current design and build state of the system is known and controlled at all times.", reference: "IBM, 'Configuration management in software engineering,' IBM. Available: https://www.ibm.com/cloud/learn/configuration-management."},
  {terminology: "Monitoring and Logging", description: "Monitoring and logging are crucial practices in DevOps. Monitoring provides feedback from operations and aids in understanding a system's performance and behavior. Logging provides the ability to analyze a discrete sequence of events in a system, which can help in troubleshooting and performance tuning.", reference: "Elastic, 'Logging vs. monitoring,' Elastic. Available: https://www.elastic.co/what-is/elk-stack/"},
  {terminology: "Cloud Computing", description: "Cloud Computing is the on-demand availability of computer system resources, especially data storage (cloud storage) and computing power, without direct active management by the user. The term is generally used to describe data centers available to many users over the Internet.", reference: "Microsoft, 'What is cloud computing? A beginner’s guide,' Microsoft Azure. Available: https://azure.microsoft.com/en-us/overview/what-is-cloud-computing/."},
  {terminology: "Ansible", description: "Ansible is an open-source software provisioning, configuration management, and application-deployment tool enabling infrastructure as code. It runs on many Unix-like systems, and can configure both Unix-like systems as well as Microsoft Windows.", reference: "Red Hat, 'Ansible,' Red Hat. Available: https://www.ansible.com/overview/it-automation"},
  {terminology: "Jenkins", description: "Jenkins is a free and open source automation server. It helps automate the parts of software development related to building, testing, and deploying, facilitating continuous integration and continuous delivery. It's a server-based system that runs in servlet containers such as Apache Tomcat.", reference: "Jenkins, 'Jenkins,' Jenkins. Available: https://www.jenkins.io/doc/book/"}
];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Cloud Glossary' ,glossery:glossery});
});

module.exports = router;